[package]
name = "templates"
version = "0.1.0"
authors = ["Vincent Prouillet <prouillet.vincent@gmail.com>"]
edition = "2018"

[dependencies]
tera = "1"
base64 = "0.13"
lazy_static = "1"
toml = "0.5"
csv = "1"
serde = "1"
serde_json = "1"
serde_derive = "1"
sha2 = "0.9"
url = "2"
nom-bibtex = "0.3"
num-format = "0.4"

errors = { path = "../errors" }
utils = { path = "../utils" }
library = { path = "../library" }
config = { path = "../config" }
imageproc = { path = "../imageproc" }
rendering = { path = "../rendering" }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["blocking"]

[dev-dependencies]
mockito = "0.31"
tempfile = "3"

[features]
rust-tls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/default-tls"]
